<?php

/**
 * This app showss the minimum amount of code needed for an app.
 */
$options = array(
    'wrapper' => 'main_content',
    'incmethod' => 'overwrite',
    'incpages' => array('homepage'),
    'ignorepages' => array(),
); // options array determines how an apps output is incorporated into the page
$output = '<p>Welcome to the SDM CMS. This homepage is being generated by the helloWorld app which developers should check out to see an example of just how easy it is to create an app for the SDM CMS.</p>'; // this string will be sent to the pages in the incpages array, or all pages if incpages is empty or not set
$devmode = FALSE; // if set to TRUE then dev data about the app output will be displayed on the page as well
$sdmassembler->incorporateAppOutput($sdmassembler_dataObject, $output, $options, $devmode);