<?php

// app description page | if you visit YOURSITE.com/index.php?page=SdmDevMenu this output will be dsiplayed
$sdmassembler->sdmAssemblerIncorporateAppOutput($sdmassembler_dataObject, '<h2>DEV MENU</h2><p>The SDM DEV MENU app outputs a menu that has links to all pages available in core, and any page that matches the name of an enabled app. For now the meni itself is restricted to the user role "root", and the SdmDevMenu app page is not restricted at all. This is for testing the new role checking being done before loading our apps.</p>', array('wrapper' => 'main_content', 'incmethod' => 'overwrite', 'incpages' => array('SdmDevMenu')));
// add a dev menu to all pages that includes links to all pages and enabled apps
$pages = $sdmassembler->sdmCoreDetermineAvailablePages();
// Possibly incorporate the following few lines that put together a list of available apps and pages into one array into the sdmCoreDetermineAvailablePages() method
$enabledApps = json_decode(json_encode($sdmassembler->sdmCoreDetermineEnabledApps()), TRUE);
$availablePages = array_merge($pages, $enabledApps);
$devMenu = '<!-- Dev Menu " Generated by core app SDM DEV TOOLS --><div><p>Dev Menu</p><ul>';
foreach ($availablePages as $link) {
    $devMenu .= '<li><a href="' . $sdmassembler->sdmCoreGetRootDirectoryUrl() . '/index.php?page=' . $link . '">' . $link . '</a></li>';
}
$devMenu .= '</ul></div><!-- End Dev Menu -->';
// incorporate devmenu
$sdmassembler->sdmAssemblerIncorporateAppOutput($sdmassembler_dataObject, $devMenu, array('wrapper' => 'side-menu', 'incmethod' => 'append', 'incpages' => $availablePages, 'roles' => array('root')));
