<?php

/* Incorporate output for app generated page. */
$sdmassembler->sdmAssemblerIncorporateAppOutput('
<h2>DEV MENU</h2><p>The SDM DEV MENU app outputs a menu that has links to all
pages available in core, and any page that matches the name of an enabled app.
For now the meni itself is restricted to the user role "root", and the SdmDevMenu
app page is not restricted at all. This is for testing the new role checking
being done before loading our apps.</p>',
    array('wrapper' => 'main_content', 'incmethod' => 'overwrite', 'incpages' => array('SdmDevMenu'))
);

/* Determine available pages */
$pages = $sdmassembler->sdmCoreListAvailablePages();

/* Determine enabled apps */
$enabledApps = json_decode(json_encode($sdmassembler->sdmCoreDetermineEnabledApps()), true);

/* Merge the $pages and $enabledApps arrays so we have an array that represents all
pages and enabled apps as available pages */
$availablePages = array_merge($pages, $enabledApps);

/* Create Dev Menu. | The Dev Menu provides links to all pages that match the name of an enabled app. */
$devMenu = '<!-- Dev Menu " Generated by core app SDM DEV TOOLS --><div><p>Dev Menu</p><ul>';
foreach ($availablePages as $link) {
    $devMenu .= '<li><a href="' . $sdmassembler->sdmCoreGetRootDirectoryUrl() . '/index.php?page=' . $link . '">' . $link . '</a></li>';
}
$devMenu .= '</ul></div><!-- End Dev Menu -->';

/* Incorporate dev menu into all pages in core and any app generated pages that share the name of an enabled app. */
$sdmassembler->sdmAssemblerIncorporateAppOutput($devMenu, array('wrapper' => 'side-menu', 'incmethod' => 'append', 'incpages' => $availablePages, 'roles' => array('all')));
