<?php

/**
 * The SdmCore class provides methods for interacting with the SDM Core.
 * Additionally, the SdmCore is responsible for initializing, configuring, and
 * starting up the SDM CMS
 *
 * @author Sevi Donnelly Foreman
 *
 * @todo create a method that formats strings into camel case that can be used by developers and by the CMS internally.
 * @todo create methods for use with a DATABASE so Admin can choose between storing site data in a json file or a DATABASE
 *
 * @property object $DataObject This object represents the data stored in the site's data.json file.
 *                              Note: By default all pages but the current requested page are excluded
 *                              from this object.
 *
 * @property string $RootDirectoryPath Path to the site's root directory.
 *
 * @property string $RootDirectoryUrl Site's root url.
 *
 * @property string $CoreDirectoryPath Path to the site's core directory.
 *
 * @property string $CoreDirectoryUrl Url to site's core directory.
 *
 * @property string $ConfigurationDirectoryPath Path to the site's configuration directory.
 *
 * @property string $ConfigurationDirectoryUrl Url to site's configuration directory.
 *
 * @property string $IncludesDirectoryPath Path to the site's includes directory.
 *
 * @property string $ThemesDirectoryPath Path to the site's themes directory.
 *
 * @property string $ThemesDirectoryUrl Url to site's themes directory.
 *
 * @property string $CurrentTheme The name of the current theme.
 *
 * @property string $CurrentThemeDirectoryPath Path to the current theme's directory.
 *
 * @property string $CurrentThemeDirectoryUrl Url to current themes directory.
 *
 * @property string $UserAppDirectoryPath Path to the site's user app directory.
 *
 * @property string $UserAppDirectoryUrl Url to site's user app directory.
 *
 * @property string $CoreAppDirectoryPath Path to the site's core app directory.
 *
 * @property string $CoreAppDirectoryUrl Url to site's core app directory.
 *
 * @property string $DataDirectoryPath Path to the site's data directory. This is where data.json is stored.
 *
 * @property string $DataDirectoryUrl Url to site's data directory. This directory is where data.json is stored.
 *
 * @property string $requestedPage The name of the requested page.
 *
 * @property array $availablePages Array of available pages.
 *                                 Note: Only pages stored in data.json will be listed in this array.
 *                                       Pages generated by apps will not be listed in this array.
 */
class SdmCore
{
    protected $DataObject;
    private $RootDirectoryPath;
    private $RootDirectoryUrl;
    private $CoreDirectoryPath;
    private $CoreDirectoryUrl;
    private $ConfigurationDirectoryPath;
    private $ConfigurationDirectoryUrl;
    private $IncludesDirectoryPath;
    private $ThemesDirectoryPath;
    private $ThemesDirectoryUrl;
    private $CurrentTheme;
    private $CurrentThemeDirectoryPath;
    private $CurrentThemeDirectoryUrl;
    private $UserAppDirectoryPath;
    private $UserAppDirectoryUrl;
    private $CoreAppDirectoryPath;
    private $CoreAppDirectoryUrl;
    private $DataDirectoryPath;
    private $DataDirectoryUrl;
    private $requestedPage;
    private $availablePages;

    /**
     * SdmCore constructor.
     */
    final public function __construct()
    {
        /* Filter this directories path to determine the site's root directory. */
        $this->RootDirectoryPath = str_replace('/core/includes', '', __DIR__);

        /* Use $_SERVER['HTTP_HOST'] and $_SERVER['PHP_SELF'] to determine site's root url.
         *
         * Filter out the names of files and directories found in the site's root directory
         * to avoid long strings of trailing slashes in urls generated by components that
         * use this property to build site urls.
         *
         * During the development of the SDM CMS when using this property to build urls
         * in themes and apps links would often end up looking like:
         *
         *  <a href="http://example.com//////index.php?page=homepage">Homepage</a>
         *
         * Removing the the names of files and directories found in the site's root directory,
         * including the preceding slash, solved this problem.
         *
         */

        /* First get the names of the files and directories in the root directory. */
        $rootFiles = scandir($this->RootDirectoryPath);

        /* Build array of files to filter, adding a forward slash to each root file and directory name. */
        $filesToFilter = array();
        foreach ($rootFiles as $rootFile) {
            $filesToFilter[] = '/' . $rootFile;
        }

        /* Build root url. */
        $this->RootDirectoryUrl = str_replace($filesToFilter, '', 'http://' . $_SERVER['HTTP_HOST'] . $_SERVER['PHP_SELF']);

        /* Build path to site's core directory. */
        $this->CoreDirectoryPath = $this->sdmCoreGetRootDirectoryPath() . '/core';

        /* Build url to site's core directory. */
        $this->CoreDirectoryUrl = $this->sdmCoreGetRootDirectoryUrl() . '/core';

        /* Build path to site's configuration directory. */
        $this->ConfigurationDirectoryPath = $this->sdmCoreGetCoreDirectoryPath() . '/config';

        /* Build url to site's configuration directory. */
        $this->ConfigurationDirectoryUrl = $this->sdmCoreGetCoreDirectoryUrl() . '/config';

        /* Build path to site's includes directory. */
        $this->IncludesDirectoryPath = $this->sdmCoreGetCoreDirectoryPath() . '/includes';

        /* Build path to site's themes directory. */
        $this->ThemesDirectoryPath = $this->sdmCoreGetRootDirectoryPath() . '/themes';

        /* Build url to site's themes directory. */
        $this->ThemesDirectoryUrl = $this->sdmCoreGetRootDirectoryUrl() . '/themes';

        /* Build path to site's user app directory. */
        $this->UserAppDirectoryPath = $this->sdmCoreGetRootDirectoryPath() . '/apps';

        /* Build url to site's user app directory. */
        $this->UserAppDirectoryUrl = $this->sdmCoreGetRootDirectoryUrl() . '/apps';

        /* Build path to site's core app directory. */
        $this->CoreAppDirectoryPath = $this->sdmCoreGetCoreDirectoryPath() . '/apps';

        /* Build url to site's core app directory. */
        $this->CoreAppDirectoryUrl = $this->sdmCoreGetCoreDirectoryUrl() . '/apps';

        /* Build path to site's data directory. */
        $this->DataDirectoryPath = $this->sdmCoreGetCoreDirectoryPath() . '/sdm';

        /* Build url to site's data directory. */
        $this->DataDirectoryUrl = $this->sdmCoreGetCoreDirectoryUrl() . '/sdm';

        /* Determine requested page. */
        $this->requestedPage = (isset($_GET['page']) && $_GET['page'] != '' ? $_GET['page'] : 'homepage');

        /* Load the DataObject if it is not already loaded. */
        $this->DataObject = (isset($this->DataObject) ? $this->DataObject : $this->sdmCoreLoadDataObject());

        /* Determine current theme. */
        $this->CurrentTheme = $this->sdmCoreDetermineCurrentTheme();

        /* Build path to current theme's directory. */
        $this->CurrentThemeDirectoryPath = $this->sdmCoreGetThemesDirectoryPath() . '/' . $this->sdmCoreDetermineCurrentTheme();

        /* Build url to current theme's directory. */
        $this->CurrentThemeDirectoryUrl = $this->sdmCoreGetThemesDirectoryUrl() . '/' . $this->sdmCoreDetermineCurrentTheme();

        /* $this->availablePages is set internally by sdmCoreLoadDataObject(); */
    }

    /**
     * Returns the path to the site's root directory.
     * @return string Returns the path to the site's root directory as a string.
     */
    final public function sdmCoreGetRootDirectoryPath()
    {
        return $this->RootDirectoryPath;
    }

    /**
     * Returns the url to the site's root directory. (i.e., The sites root url.)
     * @return string Returns the url to the site's root directory as a string.
     */
    final public function sdmCoreGetRootDirectoryUrl()
    {
        return $this->RootDirectoryUrl;
    }

    /**
     * Returns the path to the site's core directory.
     * @return string Returns the path to the site's core directory as a string.
     */
    final public function sdmCoreGetCoreDirectoryPath()
    {
        return $this->CoreDirectoryPath;
    }

    /**
     * Returns the url to the site's core directory
     * @return string The url to the site's core directory as a string.
     */
    final public function sdmCoreGetCoreDirectoryUrl()
    {
        return $this->CoreDirectoryUrl;
    }

    /**
     * Builds the DataObject from the data loaded from data.json.
     *
     * @param bool $requestPageOnly If set to true only the currently requested page
     *                              will exist in the DataObject, if set to false
     *                              then all pages stored in data.json will exist
     *                              in the DataObject.
     *
     * @return object The DataObject built from the data loaded from data.json.
     *
     */
    final public function sdmCoreLoadDataObject($requestPageOnly = true)
    {
        /* Determine requested page. */
        $requestedPage = $this->sdmCoreDetermineRequestedPage();

        /* Load json string from data.json via curl. */
        $coreJson = $this->sdmCoreCurlGrabContent($this->sdmCoreGetDataDirectoryUrl() . '/data.json');

        /* Decode json to get initial $dataObject. */
        $dataObject = json_decode($coreJson);

        /** Build available pages array to be stored in the availablePages property of this class. **/

        /* Create array of available pages in unmodified $dataObject. */
        $availablePages = array_keys(get_object_vars($dataObject->content));

        /* Create array of available pages formatted for display to be used as array keys. */
        $availablePagesKeys = array_map('ucwords', $availablePages);

        /* Create core availablePages array using $availablePagesKeys and $availablePages arrays */
        $this->availablePages = array_combine($availablePagesKeys, $availablePages);

        /* If $requestPageOnly === true remove all pages but the requested page from the DataObject. */
        if ($requestPageOnly === true) {
            /* Get the requested pages page content if it exists. This will be used to restore $datObject->content
               after it is unset. If it does not exist create a placeholder object for the requested page in
               case the requested page's content is generated by an app. */
            $requestedPageContent = (isset($dataObject->content->$requestedPage) === true ? $dataObject->content->$requestedPage : new stdClass());

            /* Unset $dataObject->content to remove all pages. */
            unset($dataObject->content);

            /* Initialize new object to be stored in $dataObject->content. */
            $dataObject->content = new stdClass();

            /* Add $requestedPage back into $dataObject->content */
            $dataObject->content->$requestedPage = $requestedPageContent;
        }
        return $dataObject;
    }

    /**
     * Returns the name of the requested page.
     * @return string The name of the requested page as a string.
     */
    final public function sdmCoreDetermineRequestedPage()
    {
        return $this->requestedPage;
    }

    /**
     * Fetches data from the specified $url via curl.
     *
     * NOTE: This method will log an error if $url is not a string.
     *
     * @param string $url The url we are fetching data from.
     *
     * @param array $post Array of post data to send, if array is empty
     * no post data will be sent.
     *
     *
     * @return string Returns results as a string of HTML, or false on failure.
     *                Note: Bad urls may return a string representing a 404 not found file.
     *                      They also may return the boolean false.
     */
    final public function sdmCoreCurlGrabContent($url, array $post = array())
    {
        /* If the string value of $url is not equal to $url than url is not a string. */
        if (strval($url) !== $url) {
            error_log('Bad type passed to SdmCore()->sdmCoreCurlGrabContent(). $url must be a string, $url passed in was type : ' . gettype($url) . '.');
        }
        /* Initialize curl session */
        $ch = curl_init();

        /* Set user agent. */
        $userAgent = $_SERVER['HTTP_USER_AGENT'];

        /* Set curl options. */
        curl_setopt($ch, CURLOPT_URL, $url);
        curl_setopt($ch, CURLOPT_COOKIESESSION, false);
        curl_setopt($ch, CURLOPT_USERAGENT, $userAgent);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_FOLLOWLOCATION, true);

        /* If any post data exists use it. */
        if (isset($post) && !empty($post)) {
            curl_setopt($ch, CURLOPT_POST, true);
            curl_setopt($ch, CURLOPT_POSTFIELDS, http_build_query($post));
        }

        /* Perform curl request. */
        $data = curl_exec($ch);

        /* Close curl session. */
        curl_close($ch);

        /* Return the $data. Will either be a string, or the boolean false. */
        return $data;
    }

    /**
     * Returns the url to the data directory.
     * @return string The url to the data directory as a string.
     */
    final public function sdmCoreGetDataDirectoryUrl()
    {
        return $this->DataDirectoryUrl;
    }

    /**
     * Determines the name of the current theme.
     * @return string The name of the current theme as a string.
     */
    final public function sdmCoreDetermineCurrentTheme()
    {
        return $this->DataObject->settings->theme;
    }

    /**
     * Returns the path to the site's themes directory.
     * (i.e., the directory where all themes are kept)
     * @return string The path to the site's themes directory as a string.
     */
    final public function sdmCoreGetThemesDirectoryPath()
    {
        return $this->ThemesDirectoryPath;
    }

    /**
     * Returns the url to the site's themes directory. (i.e., the directory where all themes are kept).
     * @return string The url to the site's themes directory as a string.
     */
    final public function sdmCoreGetThemesDirectoryUrl()
    {
        return $this->ThemesDirectoryUrl;
    }


    /**
     * Returns get_object_vars() for the calling object.
     *
     * @return array An associative array of defined object accessible non-static properties for the
     * specified object in scope. If a property has not been assigned a value, it's value will be
     * represented as null.
     */
    public function info()
    {
        return get_object_vars($this);
    }

    /**
     * Returns the url to the site's current theme's directory.
     * @return string The url to the directory for the sites current theme as a string.
     */
    final public function sdmCoreGetCurrentThemeDirectoryUrl()
    {
        return $this->CurrentThemeDirectoryUrl;
    }

    /**
     * Returns the url to the user apps directory.
     * @return string The url to the user apps directory as a string.
     */
    final public function sdmCoreGetUserAppDirectoryUrl()
    {
        return $this->UserAppDirectoryUrl;
    }

    /**
     * Returns the url to the user apps directory.
     * @return string The url to the user apps directory as a string.
     */
    final public function sdmCoreGetCoreAppDirectoryUrl()
    {
        return $this->CoreAppDirectoryUrl;
    }

    /**
     * Returns the path to the data directory.
     * @return string The path to the data directory as a string.
     */
    final public function sdmCoreGetDataDirectoryPath()
    {
        return $this->DataDirectoryPath;
    }

    /**
     * Returns the core DataObject property that holds the DataObject created from the data in data.json.
     * @return object The core data object created from the data in data.json.
     */
    final public function sdmCoreGetDataObject()
    {
        return $this->DataObject;
    }

    /**
     * Configure PHP settings and Core settings.
     * @todo: move ini_set() settings into the settings property of the DataObject so they are
     *        stored instead of hardcoded.
     * @return bool Returns true regardless of success.
     */
    final public function sdmCoreConfigureCore()
    {
        /* Turn on error reporting | @todo make this reflect site settings so admin can turn on or off based on weather in dev or not. */
        error_reporting(E_ALL | E_STRICT | E_NOTICE);
        /** modify our ini settings to fit the needs of our CMS */
        // ERRORS //
        ini_set('log_errors', '1'); // will force php to log all errors to the Server's log files
        ini_set('error_log', $this->sdmCoreGetCoreDirectoryPath() . '/logs/sdm_core_errors.log');
        ini_set('display_errors', 0); // this line should be commented out once out of dev
        // MISC //
        ini_set('auto_detect_line_endings', true); // enables PHP to inter-operate with Macintosh systems @see "http://www.php.net/manual/en/filesystem.configuration.php#ini.auto-detect-line-endings" for more information | the slight performance penalty is worth insuring that PHP's file functions will be able to determine the end of lines on all OS's
        // SESSIONS //
        ini_set('session.use_trans_sid', 0);
        ini_set('session.use_only_cookies', 1);
        ini_set('session.hash_function', 'sha512');
        ini_set('session.hash_bits_per_character', 6);
        $minutes = array_product([20, 60]); // calculate minutes in seconds
        ini_set('session.gc_maxlifetime', $minutes); // set in seconds | determines how a long a session file can exist before it becomes eligible for Garbage Collection
        ini_set('session.gc_probability', 2); // chance that GC will occur
        ini_set('session.gc_divisor', 100); // probability divisor, if gc_probability is 50 and gc_divisor is 100 then there is a 50% chance of GC (i.e. 50/100)
        // set include path
        set_include_path($this->sdmCoreGetIncludesDirectoryPath());
        // include timezone file
        require($this->sdmCoreGetConfigurationDirectoryPath() . '/timezone.php');
        return true;
    }

    /**
     * <p>Returns the path to the SDM CMS includes directory</p>
     * @return string <p>the path to the SDM CMS includes directory as a string.</p>
     */
    final public function sdmCoreGetIncludesDirectoryPath()
    {
        return $this->IncludesDirectoryPath;
    }

    /**
     * <p>Returns the path to the SDM CMS configuration directory</p>
     * @return string <p>the path to the SDM CMS configuration directory as a string.</p>
     */
    final public function sdmCoreGetConfigurationDirectoryPath()
    {
        return $this->ConfigurationDirectoryPath;
    }

    /**
     * <p>Returns the path to the SDM CMS configuration directory</p>
     * @return string <p>the path to the SDM CMS configuration directory as a string.</p>
     */
    final public function sdmCoreGetConfigurationDirectoryUrl()
    {
        return $this->ConfigurationDirectoryUrl;
    }

    /**
     * <p>Reads an array and outputs its data as html via PHP's <b><i>echo</i></b></p>.
     * @param array $array : <p>The array to read</p>
     * @param bool $sub : <p>Set internally, determines if were handling a sub array of the
     * parent array</p>
     * @param string $parent The parent item. Only used if $sub is true.
     * @return bool <p>Returns true regardless of success. This function is simply used to
     * echo an array's data so if it cant read the array the array is corrupted and needs
     * to be re-structured</p>
     */
    final public function sdmCoreSdmReadArray($array, $sub = false, $parent = '')
    {
        $style = 'border:1px dashed limegreen;border-radius:3px;margin:25px;padding:12px;width:90%;overflow:auto;background:#000000;color:#ffffff;';
        echo '<div style="' . $style . '">';
        echo($sub === false ? '' : "<i style='color:#00CCFF;'>{$parent} (<i style='color:aqua;'>" . gettype($array) . "</i>) <span style='color:#00BB00;font-size:.7em;'>Element Count: " . count($array) . "</span> => </i>");
        if (is_bool($array) || is_string($array) || is_integer($array)) {
            $v = $array;
            unset($array);
            $array = (is_bool($v) ? array(gettype($v) => ($v === true ? 'true' : 'false')) : array(gettype($v) => strval($v)));
        }
        foreach ($array as $key => $value) {
            switch (is_array($value)) {
                case true:
                    self::sdmCoreSdmReadArray($value, true, $key);
                    break;
                default:
                    if (is_object($value)) {
                        echo($sub === false ? '<p><b style="color:#00CCFF;"><i>' . (isset($key) ? strval($key) : 'unknown_object') . '</i></b> (<i style="color:aqua;">object</i>)</p>' : '<p><ul><li><b style="color:#00FF99;"><i>' . (isset($key) ? strval($key) : 'unknown_object') . '</i></b>(<i style="color:aqua;">object</i>)</li></ul></p>');
                        self::sdmCoreSdmReadArray(json_decode(json_encode($value), true));
                    } else {
                        echo($sub === false ? "<p><xmp style='display:inline;color:#00CCFF'>{$key}</xmp> (<i style='color:aqua;'>" . gettype($value) . "</i>) " . (gettype($value) === 'string' ? '<span style="color:#00DDFF;font-size:.7em;font-style: italic;">String Length: ' . strlen($value) . '</span>' : '') . " => <xmp style='display:inline;color:#00CC99'>{$value}</xmp></p>" : "<p><ul><li><xmp style='display:inline;color:#00CC99'>{$key}</xmp> (<i style='color:aqua;'>" . gettype($value) . "</i>) " . (gettype($value) === 'string' ? '<span style="color:#00DDFF;font-size:.7em;font-style: italic;">String Length: ' . strlen($value) . '</span>' : '') . " => <xmp style='display:inline;color:#00CC99'>{$value}</xmp></li></ul></p>");
                    }
                    break;
            }
        }
        echo '</div>';
        return true;
    }

    /**
     *  Attempts to return a directory listing for the specified directory (i.e., $directoryName)
     * @param string $directoryName <p>The name of the directory to create a listing of.</p>
     * @param string $directoryLocationReference <p>The name of a directory to be used as a starting reference point to search for the directory we want to create a listing for.
     * <br><br>
     * <i>$this->sdmCoreGetDirectoryListing('', 'core')</i>
     * <br><br>
     * would return a directory listing for '<b>SITESROOTURL</b>/core/'. (Note: passing an empty string will return the name of the directory being used as a locational reference.(i.e., $directoryLocationReference)
     * <br><br><b>(Note: there is one special value you can pass to this parameter, the 'CURRENT_THEME' value will return a directory listing for the current theme)</b>
     * </p>
     * @return array A directory listing for $directoryName as an array.
     */
    final public function sdmCoreGetDirectoryListing($directoryName, $directoryLocationReference)
    {
        switch ($directoryLocationReference) {
            // search for directory in site root
            case 'root':
                return scandir($this->sdmCoreGetRootDirectoryPath() . '/' . $directoryName);
                break;
            // search for directory in site core
            case 'core':
                return scandir($this->sdmCoreGetCoreDirectoryPath() . '/' . $directoryName);
                break;
            // search for directory in site themes
            case 'themes':
                return scandir($this->sdmCoreGetRootDirectoryPath() . '/themes/' . $directoryName);
                break;
            case 'CURRENT_THEME':
                return scandir($this->sdmCoreGetCurrentThemeDirectoryPath() . '/' . $directoryName);
                break;
            case 'apps':
                return scandir($this->sdmCoreGetUserAppDirectoryPath() . '/' . $directoryName);
                break;
            case 'coreapps':
                return scandir($this->sdmCoreGetCoreAppDirectoryPath() . '/' . $directoryName);
                break;
            case 'userapps':
                return scandir($this->sdmCoreGetUserAppDirectoryPath() . '/' . $directoryName);
                break;
            default:
                return array('error' => 'Unable to find requested directory');
                break;
        }
    }

    /**
     * <p>Returns the path to the current chosen themes directory</p>
     * @return string <p>The path to the directory for the sites current theme as a string.</p>
     */
    final public function sdmCoreGetCurrentThemeDirectoryPath()
    {
        return $this->CurrentThemeDirectoryPath;
    }

    /**
     * <p>Returns the path to the user apps directory</p>
     * @return string <p>The path to the user apps directory.</p>
     */
    final public function sdmCoreGetUserAppDirectoryPath()
    {
        return $this->UserAppDirectoryPath;
    }

    /**
     * <p>Returns the path to the core apps directory</p>
     * @return string <p>The path to the core apps directory.</p>
     */
    final public function sdmCoreGetCoreAppDirectoryPath()
    {
        return $this->CoreAppDirectoryPath;
    }

    /**
     * Determines what pages exist for the current site returning an indexed array of all the pages.
     * This method is used internally, and can also be used by developers to
     * do things like create a security checks, for instance insuring only pages
     * that actually exist and are part of the site are accessed.
     * @return array An associative array structured array('Page Name' => 'pageName');
     *
     */
    final public function sdmCoreDetermineAvailablePages()
    {
        return $this->availablePages;
    }

    /**
     * <p>Returns object stored in DataObject->settings->enabledapps.</p>
     * @return object <p>$this->DataObject->settings->enabledapps.</p>
     */
    final public function sdmCoreDetermineEnabledApps()
    {
        return $this->DataObject->settings->enabledapps;
    }

    /**
     * Takes a value and filters it so it is machine safe, i.e., only letters and numbers.
     * If an array is passed then each of it's values will be passed to SdmCoreGenerateMachineName()
     * and an array with the filtered values will be returned.
     *
     * @param mixed $value The value to convert into a machine safe string. If an array is passed each value in the
     *                     array will be filtered.
     *
     * @return mixed A machine safe string. If an array was passed then it's values will be filtered recursively and
     *               the filtered array will be returned.
     */
    final public function SdmCoreGenerateMachineName($value)
    {
        $targetChars = str_split('~!@#$%^&*()+|}{":;?> <`\'\\Ω≈ç√∫˜≤≥÷åß∂ƒ©˙∆˚¬…æœ∑´†¥¨ˆπ“‘«`™£¢∞§¶•ªº–≠¸˛Ç◊ı˜Â¯˘¿ÅÍÎÏ˝ÓÔÒÚÆŒ„´‰ˇÁ¨ˆØ∏”’»`⁄€‹›ﬁﬂ‡°·‚—±');
        switch (is_array($value)) {
            case true:
                foreach ($value as $k => $v) {
                    unset($value[$k]);
                    $value[$k] = SdmCore::SdmCoreGenerateMachineName($v);
                    unset($k);
                    unset($v);
                }
                break;

            default:
                $value = str_replace($targetChars, '_', $value);
                break;
        }
        // remove any duplicate underscores
        $machineValue = preg_replace('/[_]+/', '_', $value);
        return strtolower($machineValue);
    }

    /**
     * Returns a substring between two strings from a string.
     *
     * i.e.,
     * sdmCoreStrSlice('Some string to slice.', 'to','.'); // returns 'slice'
     *
     * Note: Neither the $start or $end strings will be included in the slice.
     *
     * @param string $string String to get slice from.
     *
     * @param string $start Starting string, i.e., the chars to start the slice after.
     *
     * @param string $end The ending string, i.e., the chars to end the slice at.
     *
     * @return string The slice of the string between $start and $end.
     */
    final public function sdmCoreStrSlice($string, $start, $end)
    {
        $string = " " . $string;
        $ini = strpos($string, $start);
        if ($ini == 0) {
            return "";
        }
        $ini += strlen($start);
        $len = strpos($string, $end, $ini) - $ini;
        return substr($string, $ini, $len);
    }

}
