<?php

/**
 * The SdmCore class provides methods for interacting with the SDM Core.
 * Additionally, the SdmCore is responsible for initializing, configuring, and
 * starting up the SDM CMS
 *
 * @author Sevi Donnelly Foreman
 *
 * @todo create a method that formats strings into camel case that can be used by developers and by the CMS internally.
 * @todo create methods for use with a DATABASE so Admin can choose between storing site data in a json file or a DATABASE
 *
 * @property object $DataObject This object represents the data stored in the site's data.json file.
 *                              Note: By default all pages but the current requested page are excluded
 *                              from this object.
 *
 * @property string $RootDirectoryPath Path to the site's root directory.
 *
 * @property string $RootDirectoryUrl Site's root url.
 *
 * @property string $CoreDirectoryPath Path to the site's core directory.
 *
 * @property string $CoreDirectoryUrl Url to site's core directory.
 *
 * @property string $ConfigurationDirectoryPath Path to the site's configuration directory.
 *
 * @property string $ConfigurationDirectoryUrl Url to site's configuration directory.
 *
 * @property string $IncludesDirectoryPath Path to the site's includes directory.
 *
 * @property string $ThemesDirectoryPath Path to the site's themes directory.
 *
 * @property string $ThemesDirectoryUrl Url to site's themes directory.
 *
 * @property string $CurrentTheme The name of the current theme.
 *
 * @property string $CurrentThemeDirectoryPath Path to the current theme's directory.
 *
 * @property string $CurrentThemeDirectoryUrl Url to current themes directory.
 *
 * @property string $UserAppDirectoryPath Path to the site's user app directory.
 *
 * @property string $UserAppDirectoryUrl Url to site's user app directory.
 *
 * @property string $CoreAppDirectoryPath Path to the site's core app directory.
 *
 * @property string $CoreAppDirectoryUrl Url to site's core app directory.
 *
 * @property string $DataDirectoryPath Path to the site's data directory. This is where data.json is stored.
 *
 * @property string $DataDirectoryUrl Url to site's data directory. This directory is where data.json is stored.
 *
 * @property string $requestedPage The name of the requested page.
 *
 * @property array $availablePages Array of available pages.
 *                                 Note: Only pages stored in data.json will be listed in this array.
 *                                       Pages generated by apps will not be listed in this array.
 */
class SdmCore
{
    protected $DataObject;
    private $RootDirectoryPath;
    private $RootDirectoryUrl;
    private $CoreDirectoryPath;
    private $CoreDirectoryUrl;
    private $ConfigurationDirectoryPath;
    private $ConfigurationDirectoryUrl;
    private $IncludesDirectoryPath;
    private $ThemesDirectoryPath;
    private $ThemesDirectoryUrl;
    private $CurrentTheme;
    private $CurrentThemeDirectoryPath;
    private $CurrentThemeDirectoryUrl;
    private $UserAppDirectoryPath;
    private $UserAppDirectoryUrl;
    private $CoreAppDirectoryPath;
    private $CoreAppDirectoryUrl;
    private $DataDirectoryPath;
    private $DataDirectoryUrl;
    private $requestedPage;
    private $availablePages;

    /**
     * SdmCore constructor.
     */
    final public function __construct()
    {
        /* Filter this directories path to determine the site's root directory. */
        $this->RootDirectoryPath = str_replace('/core/includes', '', __DIR__);

        /* Use $_SERVER['HTTP_HOST'] and $_SERVER['PHP_SELF'] to determine site's root url.
         *
         * Filter out the names of files and directories found in the site's root directory
         * to avoid long strings of trailing slashes in urls generated by components that
         * use this property to build site urls.
         *
         * During the development of the SDM CMS when using this property to build urls
         * in themes and apps links would often end up looking like:
         *
         *  <a href="http://example.com//////index.php?page=homepage">Homepage</a>
         *
         * Removing the the names of files and directories found in the site's root directory,
         * including the preceding slash, solved this problem.
         *
         */

        /* First get the names of the files and directories in the root directory. */
        $rootFiles = scandir($this->RootDirectoryPath);

        /* Build array of files to filter, adding a forward slash to each root file and directory name. */
        $filesToFilter = array();
        foreach ($rootFiles as $rootFile) {
            $filesToFilter[] = '/' . $rootFile;
        }

        /* Build root url. */
        $this->RootDirectoryUrl = str_replace($filesToFilter, '', 'http://' . $_SERVER['HTTP_HOST'] . $_SERVER['PHP_SELF']);

        /* Build path to site's core directory. */
        $this->CoreDirectoryPath = $this->sdmCoreGetRootDirectoryPath() . '/core';

        /* Build url to site's core directory. */
        $this->CoreDirectoryUrl = $this->sdmCoreGetRootDirectoryUrl() . '/core';

        /* Build path to site's configuration directory. */
        $this->ConfigurationDirectoryPath = $this->sdmCoreGetCoreDirectoryPath() . '/config';

        /* Build url to site's configuration directory. */
        $this->ConfigurationDirectoryUrl = $this->sdmCoreGetCoreDirectoryUrl() . '/config';

        /* Build path to site's includes directory. */
        $this->IncludesDirectoryPath = $this->sdmCoreGetCoreDirectoryPath() . '/includes';

        /* Build path to site's themes directory. */
        $this->ThemesDirectoryPath = $this->sdmCoreGetRootDirectoryPath() . '/themes';

        /* Build url to site's themes directory. */
        $this->ThemesDirectoryUrl = $this->sdmCoreGetRootDirectoryUrl() . '/themes';

        /* Build path to site's user app directory. */
        $this->UserAppDirectoryPath = $this->sdmCoreGetRootDirectoryPath() . '/apps';

        /* Build url to site's user app directory. */
        $this->UserAppDirectoryUrl = $this->sdmCoreGetRootDirectoryUrl() . '/apps';

        /* Build path to site's core app directory. */
        $this->CoreAppDirectoryPath = $this->sdmCoreGetCoreDirectoryPath() . '/apps';

        /* Build url to site's core app directory. */
        $this->CoreAppDirectoryUrl = $this->sdmCoreGetCoreDirectoryUrl() . '/apps';

        /* Build path to site's data directory. */
        $this->DataDirectoryPath = $this->sdmCoreGetCoreDirectoryPath() . '/sdm';

        /* Build url to site's data directory. */
        $this->DataDirectoryUrl = $this->sdmCoreGetCoreDirectoryUrl() . '/sdm';

        /* Determine requested page. */
        $this->requestedPage = (isset($_GET['page']) && $_GET['page'] != '' ? $_GET['page'] : 'homepage');

        /* Load the DataObject if it is not already loaded. */
        $this->DataObject = (isset($this->DataObject) ? $this->DataObject : $this->sdmCoreLoadDataObject());

        /* Determine current theme. */
        $this->CurrentTheme = $this->sdmCoreDetermineCurrentTheme();

        /* Build path to current theme's directory. */
        $this->CurrentThemeDirectoryPath = $this->sdmCoreGetThemesDirectoryPath() . '/' . $this->sdmCoreDetermineCurrentTheme();

        /* Build url to current theme's directory. */
        $this->CurrentThemeDirectoryUrl = $this->sdmCoreGetThemesDirectoryUrl() . '/' . $this->sdmCoreDetermineCurrentTheme();

        /* $this->availablePages is set internally by sdmCoreLoadDataObject(); */
    }

    /**
     * Returns the path to the site's root directory.
     * @return string Returns the path to the site's root directory as a string.
     */
    final public function sdmCoreGetRootDirectoryPath()
    {
        return $this->RootDirectoryPath;
    }

    /**
     * Returns the url to the site's root directory. (i.e., The sites root url.)
     * @return string Returns the url to the site's root directory as a string.
     */
    final public function sdmCoreGetRootDirectoryUrl()
    {
        return $this->RootDirectoryUrl;
    }

    /**
     * Returns the path to the site's core directory.
     * @return string Returns the path to the site's core directory as a string.
     */
    final public function sdmCoreGetCoreDirectoryPath()
    {
        return $this->CoreDirectoryPath;
    }

    /**
     * Returns the url to the site's core directory
     * @return string The url to the site's core directory as a string.
     */
    final public function sdmCoreGetCoreDirectoryUrl()
    {
        return $this->CoreDirectoryUrl;
    }

    /**
     * Builds the DataObject from the data loaded from data.json.
     *
     * @param bool $requestPageOnly If set to true only the currently requested page
     *                              will exist in the DataObject, if set to false
     *                              then all pages stored in data.json will exist
     *                              in the DataObject.
     *
     * @return object The DataObject built from the data loaded from data.json.
     *
     */
    final public function sdmCoreLoadDataObject($requestPageOnly = true)
    {
        /* Determine requested page. */
        $requestedPage = $this->sdmCoreDetermineRequestedPage();

        /* Load json string from data.json via curl. */
        $coreJson = $this->sdmCoreCurlGrabContent($this->sdmCoreGetDataDirectoryUrl() . '/data.json');

        /* Decode json to get initial $dataObject. */
        $dataObject = json_decode($coreJson);

        /** Build available pages array to be stored in the availablePages property of this class. **/

        /* Create array of available pages in unmodified $dataObject. */
        $availablePages = array_keys(get_object_vars($dataObject->content));

        /* Create array of available pages formatted for display to be used as array keys. */
        $availablePagesKeys = array_map('ucwords', $availablePages);

        /* Create core availablePages array using $availablePagesKeys and $availablePages arrays */
        $this->availablePages = array_combine($availablePagesKeys, $availablePages);

        /* If $requestPageOnly === true remove all pages but the requested page from the DataObject. */
        if ($requestPageOnly === true) {
            /* Get the requested pages page content if it exists. This will be used to restore $datObject->content
               after it is unset. If it does not exist create a placeholder object for the requested page in
               case the requested page's content is generated by an app. */
            $requestedPageContent = (isset($dataObject->content->$requestedPage) === true ? $dataObject->content->$requestedPage : new stdClass());

            /* Unset $dataObject->content to remove all pages. */
            unset($dataObject->content);

            /* Initialize new object to be stored in $dataObject->content. */
            $dataObject->content = new stdClass();

            /* Add $requestedPage back into $dataObject->content */
            $dataObject->content->$requestedPage = $requestedPageContent;
        }
        return $dataObject;
    }

    /**
     * Returns the name of the requested page.
     * @return string The name of the requested page as a string.
     */
    final public function sdmCoreDetermineRequestedPage()
    {
        return $this->requestedPage;
    }

    /**
     * Fetches data from the specified $url via curl.
     *
     * NOTE: This method will log an error if $url is not a string.
     *
     * @param string $url The url we are fetching data from.
     *
     * @param array $post Array of post data to send, if array is empty
     * no post data will be sent.
     *
     *
     * @return string Returns results as a string of HTML, or false on failure.
     *                Note: Bad urls may return a string representing a 404 not found file.
     *                      They also may return the boolean false.
     */
    final public function sdmCoreCurlGrabContent($url, array $post = array())
    {
        /* If the string value of $url is not equal to $url than url is not a string. */
        if (strval($url) !== $url) {
            error_log('Bad type passed to SdmCore()->sdmCoreCurlGrabContent(). $url must be a string, $url passed in was type : ' . gettype($url) . '.');
        }
        /* Initialize curl session */
        $curlSession = curl_init();

        /* Set user agent. */
        $userAgent = $_SERVER['HTTP_USER_AGENT'];

        /* Set curl options. */
        curl_setopt($curlSession, CURLOPT_URL, $url);
        curl_setopt($curlSession, CURLOPT_COOKIESESSION, false);
        curl_setopt($curlSession, CURLOPT_USERAGENT, $userAgent);
        curl_setopt($curlSession, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($curlSession, CURLOPT_FOLLOWLOCATION, true);

        /* If any post data exists use it. */
        if (isset($post) && !empty($post)) {
            curl_setopt($curlSession, CURLOPT_POST, true);
            curl_setopt($curlSession, CURLOPT_POSTFIELDS, http_build_query($post));
        }

        /* Perform curl request. */
        $data = curl_exec($curlSession);

        /* Close curl session. */
        curl_close($curlSession);

        /* Return the $data. Will either be a string, or the boolean false. */
        return $data;
    }

    /**
     * Returns the url to the data directory.
     * @return string The url to the data directory as a string.
     */
    final public function sdmCoreGetDataDirectoryUrl()
    {
        return $this->DataDirectoryUrl;
    }

    /**
     * Determines the name of the current theme.
     * @return string The name of the current theme as a string.
     */
    final public function sdmCoreDetermineCurrentTheme()
    {
        return $this->DataObject->settings->theme;
    }

    /**
     * Returns the path to the site's themes directory.
     * (i.e., the directory where all themes are kept)
     * @return string The path to the site's themes directory as a string.
     */
    final public function sdmCoreGetThemesDirectoryPath()
    {
        return $this->ThemesDirectoryPath;
    }

    /**
     * Returns the url to the site's themes directory. (i.e., the directory where all themes are kept).
     * @return string The url to the site's themes directory as a string.
     */
    final public function sdmCoreGetThemesDirectoryUrl()
    {
        return $this->ThemesDirectoryUrl;
    }


    /**
     * Returns get_object_vars() for the calling object.
     *
     * @return array An associative array of defined object accessible non-static properties for the
     * specified object in scope. If a property has not been assigned a value, it's value will be
     * represented as null.
     */
    public function info()
    {
        return get_object_vars($this);
    }

    /**
     * Returns the url to the site's current theme's directory.
     * @return string The url to the directory for the sites current theme as a string.
     */
    final public function sdmCoreGetCurrentThemeDirectoryUrl()
    {
        return $this->CurrentThemeDirectoryUrl;
    }

    /**
     * Returns the url to the user apps directory.
     * @return string The url to the user apps directory as a string.
     */
    final public function sdmCoreGetUserAppDirectoryUrl()
    {
        return $this->UserAppDirectoryUrl;
    }

    /**
     * Returns the url to the user apps directory.
     * @return string The url to the user apps directory as a string.
     */
    final public function sdmCoreGetCoreAppDirectoryUrl()
    {
        return $this->CoreAppDirectoryUrl;
    }

    /**
     * Returns the path to the data directory.
     * @return string The path to the data directory as a string.
     */
    final public function sdmCoreGetDataDirectoryPath()
    {
        return $this->DataDirectoryPath;
    }

    /**
     * Returns the core DataObject property that holds the DataObject created from the data in data.json.
     * @return object The core data object created from the data in data.json.
     */
    final public function sdmCoreGetDataObject()
    {
        return $this->DataObject;
    }

    /**
     * Configures PHP settings and Core settings.
     *
     * Specifically, this method configures the PHP ini settings as defined
     * in the DataObject, sets the site's includes directory, and sets the
     * timezone for the site as defined in the DataObject.
     *
     * @return bool Returns true regardless of success.
     */
    final public function sdmCoreConfigureCore()
    {
        $settings = $this->DataObject->settings;
        /* Turn on error reporting. @todo: trying to figure out how to read these constants
        from the DataObject. Preferably from an array. */
        error_reporting(E_ALL | E_STRICT | E_NOTICE);
        foreach ($settings->iniSettings as $iniSettingName => $iniSettingValue) {
            ini_set($iniSettingName, $iniSettingValue);
        }
        /* Set include path. */
        set_include_path($this->sdmCoreGetIncludesDirectoryPath());

        /* Set timezone for scripts. */
        date_default_timezone_set($settings->iniSettings->{"date.timezone"});
        return true;
    }

    /**
     * Returns the path to the site's includes directory.
     * @return string Returns the path to the site's includes directory as a string.
     */
    final public function sdmCoreGetIncludesDirectoryPath()
    {
        return $this->IncludesDirectoryPath;
    }

    /**
     * Returns the path to the site's configuration directory.
     * @return string Returns the path to the site's configuration directory as a string.
     */
    final public function sdmCoreGetConfigurationDirectoryPath()
    {
        return $this->ConfigurationDirectoryPath;
    }

    /**
     * Returns the path to the site's configuration directory.
     * @return string Returns the path to the site's configuration directory as a string.
     */
    final public function sdmCoreGetConfigurationDirectoryUrl()
    {
        return $this->ConfigurationDirectoryUrl;
    }

    /**
     * Wraps call to sdmCoreReadArray() in an output buffer so it's output
     * can be obtained as a string instead of just being echoed to the
     * page.
     *
     * @param mixed $value The value to read.
     * @return string string The output from sdmCoreSdmReadArray() as a string.
     */
    final public function sdmCoreSdmReadArrayBuffered($value)
    {
        /* Start the output buffer. */
        ob_start();

        /* Pass $value to sdmCoreSdmReadArray() */
        $this->sdmCoreSdmReadArray($value);

        /* Get the output form the output buffer, cleanup, and turn output buffering off. */
        $output = ob_get_clean();

        /* Return the output from the output buffer. */
        return $output;
    }

    /**
     * Read the $variable and echo a formatted display of it to the current page.
     *
     * Basically, this method is the Sdm Cms's version of var_dump().
     *
     * Note: This method cannot directly handle doubles.
     *
     * i.e., The following will not work:
     *
     * $this->sdmCoreSdmReadArray(4.20420);
     *
     * Hint: This method is incredibly useful when developing themes and apps.
     *
     * Note: Passing null directly to sdmCoreSdmReadArray() will result in an empty display.
     *
     * @param mixed $variable : The variable to display.
     *
     * @param bool $sub : Set to true internally when handling nested arrays, this parameter determines if
     *                    $variable is a child of $parent. Defaults to false.
     *
     * @param string $parent The name of the $parent of the $variable. This parameter is set internally and is
     *                       only used if $sub is true. Defaults to an empty string.
     *
     * @return bool Returns true regardless of success.
     */
    final public function sdmCoreSdmReadArray($variable, $sub = false, $parent = '')
    {
        if ($this->sdmCoreSdmReadArrayGetVarName($variable) !== false) {
            echo('<div style="text-align: center">$' . $this->sdmCoreSdmReadArrayGetVarName($variable) . '</div>');
        }
        $style = 'border:1px dashed limegreen;border-radius:3px;margin:25px;padding:12px;width:90%;overflow:auto;background:#000000;color:#ffffff;';
        echo '<div style="' . $style . '">';
        echo($sub === false ? '' : "<i style='color:#00CCFF;'>{$parent} (<i style='color:aqua;'>" . gettype($variable) . "</i>) <span style='color:#00BB00;font-size:.7em;'>Element Count: " . count($variable) . "</span> => </i>");
        if (is_bool($variable) || is_string($variable) || is_integer($variable)) {
            $initialValue = $variable;
            unset($variable);
            $variable = (is_bool($initialValue) ? array(gettype($initialValue) => ($initialValue === true ? 'true' : 'false')) : array(gettype($initialValue) => strval($initialValue)));
        }
        foreach ($variable as $key => $value) {
            switch (is_array($value)) {
                case true:
                    self::sdmCoreSdmReadArray($value, true, $key);
                    break;
                default:
                    if (is_object($value)) {
                        echo($sub === false ? '<p><b style="color:#00CCFF;"><i>' . (isset($key) ? strval($key) : 'unknown_object') . '</i></b> (<i style="color:aqua;">object</i>)</p>' : '<p><ul><li><b style="color:#00FF99;"><i>' . (isset($key) ? strval($key) : 'unknown_object') . '</i></b>(<i style="color:aqua;">object</i>)</li></ul></p>');
                        self::sdmCoreSdmReadArray(json_decode(json_encode($value), true));
                    } else {
                        echo($sub === false ? "<p><xmp style='display:inline;color:#00CCFF'>{$key}</xmp> (<i style='color:aqua;'>" . gettype($value) . "</i>) " . (gettype($value) === 'string' ? '<span style="color:#00DDFF;font-size:.7em;font-style: italic;">String Length: ' . strlen($value) . '</span>' : '') . " => <xmp style='display:inline;color:#00CC99'>" . (gettype($value) === 'boolean' ? ($value === false ? 'false' : 'true') : $value) . "</xmp></p>" : "<p><ul><li><xmp style='display:inline;color:#00CC99'>{$key}</xmp> (<i style='color:aqua;'>" . gettype($value) . "</i>) " . (gettype($value) === 'string' ? '<span style="color:#00DDFF;font-size:.7em;font-style: italic;">String Length: ' . strlen($value) . '</span>' : '') . " => <xmp style='display:inline;color:#00CC99'>" . (gettype($value) === 'boolean' ? ($value === false ? 'false' : 'true') : $value) . "</xmp></li></ul></p>");
                    }
                    break;
            }
        }
        echo '</div>';
        return true;
    }

    /**
     * Looks up the name of a variable by it's value in the $GLOBALS array.
     *
     * Based on code from stack overflow @see http://stackoverflow.com/questions/255312/how-to-get-a-variable-name-as-a-string-in-php
     * NOTE: There is a small risk if two vars have the same value that the wrong
     *       index in the $GLOBALS array will be returned as the variable name.
     *       Do not rely on this, it is meant to provide information, not to be used
     *       for testing, development, type or value checks, or any important logic.
     *
     * @param $variableValue The value of the variable whose name should be returned.
     * @return bool|int|string The name of the variable, or false on failure.
     */
    final private function sdmCoreSdmReadArrayGetVarName($variableValue)
    {
        foreach ($GLOBALS as $var_name => $value) {
            if ($value === $variableValue) {
                return $var_name;
            }
        }

        return false;
    }

    /**
     * Attempts to return a directory listing for the specified directory as an array.
     *
     * The following would return a directory listing for site's core/config directory.
     *
     * $this->sdmCoreGetDirectoryListing('config', 'core'); // returns directory listing for 'core/config'
     *
     * Note: Passing an empty string to $directoryName will result in a directory listing of
     *       the $directoryLocationReference.
     *
     * $this->sdmCoreGetDirectoryListing('', 'core'); // returns directory listing for 'core'
     *
     * @param string $directoryName The name of the directory to create a listing of.
     *
     * @param string $directoryLocationReference The name of a directory to be used as
     *               a starting reference point to search for the directory we want to
     *               create a listing for.
     *
     *               Note: There is one special value you can pass to the $directoryLocationReference
     *                     parameter, the 'CURRENT_THEME' value sret the current themes root directory
     *                     as the $directoryLocationReference.
     *
     * @return array An array representing the contents of the directory at
     *               $directoryLocationReference/$directoryName, or false on failure.
     */
    final public function sdmCoreGetDirectoryListing($directoryName, $directoryLocationReference)
    {
        switch ($directoryLocationReference) {
            case 'root':
                return scandir($this->sdmCoreGetRootDirectoryPath() . '/' . $directoryName);
                break;
            case 'core':
                return scandir($this->sdmCoreGetCoreDirectoryPath() . '/' . $directoryName);
                break;
            case 'themes':
                return scandir($this->sdmCoreGetRootDirectoryPath() . '/themes/' . $directoryName);
                break;
            case 'CURRENT_THEME':
                return scandir($this->sdmCoreGetCurrentThemeDirectoryPath() . '/' . $directoryName);
                break;
            case 'apps':
                return scandir($this->sdmCoreGetUserAppDirectoryPath() . '/' . $directoryName);
                break;
            case 'coreapps':
                return scandir($this->sdmCoreGetCoreAppDirectoryPath() . '/' . $directoryName);
                break;
            case 'userapps':
                return scandir($this->sdmCoreGetUserAppDirectoryPath() . '/' . $directoryName);
                break;
            default:
                error_log('SdmCore()->sdmCoreGetDirectoryListing() failed to create directory listing for
                           directory at ' . $directoryLocationReference . '/' . $directoryName);
                return false;
                break;
        }
    }

    /**
     * Returns the path to the current chosen themes directory.
     * @return string The path to the directory for the sites current theme as a string.
     */
    final public function sdmCoreGetCurrentThemeDirectoryPath()
    {
        return $this->CurrentThemeDirectoryPath;
    }

    /**
     * Returns the path to the user apps directory.
     * @return string The path to the user apps directory.
     */
    final public function sdmCoreGetUserAppDirectoryPath()
    {
        return $this->UserAppDirectoryPath;
    }

    /**
     * Returns the path to the core apps directory.
     * @return string The path to the core apps directory.
     */
    final public function sdmCoreGetCoreAppDirectoryPath()
    {
        return $this->CoreAppDirectoryPath;
    }

    /**
     * Determines what pages exist for the current site returning an indexed array of all the pages.
     *
     * This method is used internally, and can also be used by developers to
     * do things like create a security checks, for instance insuring only pages
     * that actually exist and are part of the site are accessed.
     *
     * @return array An associative array structured array('Page Name' => 'pageName');
     *
     */
    final public function sdmCoreDetermineAvailablePages()
    {
        return $this->availablePages;
    }

    /**
     * Returns object stored in DataObject->settings->enabledapps.
     * @return object Returns $this->DataObject->settings->enabledapps.
     */
    final public function sdmCoreDetermineEnabledApps()
    {
        return $this->DataObject->settings->enabledapps;
    }

    /**
     * Takes a value and filters it so it is machine safe.
     *
     * If an array is passed then each of it's values will be passed to sdmCoreGenerateMachineName()
     * and an array with the filtered values will be returned.
     *
     * @param mixed $value The value to convert into a machine safe string. If an array is passed each value in the
     *                     array will be filtered.
     *
     * @return mixed Returns a machine safe string representation of the $value. If an array was passed then it's
     *               values will be filtered recursively and the filtered array will be returned.
     */
    final public function sdmCoreGenerateMachineName($value)
    {
        $targetChars = str_split('~!@#$%^&*()+|}{":;?> <`\'\\Ω≈ç√∫˜≤≥÷åß∂ƒ©˙∆˚¬…æœ∑´†¥¨ˆπ“‘«`™£¢∞§¶•ªº–≠¸˛Ç◊ı˜Â¯˘¿ÅÍÎÏ˝ÓÔÒÚÆŒ„´‰ˇÁ¨ˆØ∏”’»`⁄€‹›ﬁﬂ‡°·‚—±');
        switch (is_array($value)) {
            case true:
                foreach ($value as $key => $val) {
                    unset($value[$key]);
                    $value[$key] = SdmCore::sdmCoreGenerateMachineName($val);
                    unset($key);
                    unset($val);
                }
                break;

            default:
                $value = str_replace($targetChars, '_', $value);
                break;
        }
        // remove any duplicate underscores
        $machineValue = preg_replace('/[_]+/', '_', $value);
        return strtolower($machineValue);
    }

    /**
     * Returns a substring between two strings from a string.
     *
     * i.e.,
     * sdmCoreStrSlice('Some string to slice.', 'to','.'); // returns 'slice'
     *
     * Note: Neither the $start or $end strings will be included in the slice.
     *
     * @param string $string String to get slice from.
     *
     * @param string $start Starting string, i.e., the chars to start the slice after.
     *
     * @param string $end The ending string, i.e., the chars to end the slice at.
     *
     * @return string The slice of the string between $start and $end.
     */
    final public function sdmCoreStrSlice($string, $start, $end)
    {
        $string = " " . $string;
        $ini = strpos($string, $start);
        if ($ini == 0) {
            return "";
        }
        $ini += strlen($start);
        $len = strpos($string, $end, $ini) - $ini;
        return substr($string, $ini, $len);
    }

}
