<?php

// add a dev menu to all pages that includes links to all pages and enabled apps
$pages = $sdmcore->sdmCoreDetermineAvailablePages();
// Possibly incorporate the following few lines that put together a list of available apps and pages into one array into the sdmCoreDetermineAvailablePages() method
$enabledApps = json_decode(json_encode($sdmcore->sdmCmsDetermineEnabledApps()), TRUE);
$availablePages = array_merge($pages, $enabledApps);
$devMenu = '<!-- Dev Menu " Generated by core app SDM DEV TOOLS --><div style="color:aqua;background:#000000;padding:20px;border:1px solid black;border-radius:20px;"><h3>Dev Menu</h3><ul>';
foreach ($availablePages as $link) {
    $devMenu .= '<li><a href="' . $sdmcore->getRootDirectoryUrl() . '/index.php?page=' . $link . '">' . $link . '</a></li>';
}
$devMenu .= '</ul></div><!-- End Dev Menu -->';
$sdmassembler->incorporateAppOutput($sdmassembler_dataObject, $devMenu, array('wrapper' => 'topmenu', 'incmethod' => 'prepend', 'incpages' => $availablePages)); // use the links array we genertated that lists all available pages and enabled apps as the incpages array so all pages incroporate this menu
// add a dev tools menu to all pages related to this app
$sdmassembler->incorporateAppOutput($sdmassembler_dataObject, trim('
    <p><a href="' . $sdmcore->getRootDirectoryUrl() . '/index.php?page=core">Core</a></p>
    <p><a href="' . $sdmcore->getRootDirectoryUrl() . '/index.php?page=errors">Error Log</a></p>
    <p><a href="' . $sdmcore->getRootDirectoryUrl() . '/index.php?page=clearErrorLog">Clear Error Log</a></p>
    <div style="border:3px solid red; border-radius:25px;background: black; color: #CC0066; padding: 20px; margin: 3px 3px 3px 3px;"><p><a href="' . $sdmcore->getRootDirectoryUrl() . '/index.php?page=reset">Reset Site</a></p><p><i><b>NOTE: THIS WILL ERASE ALL SITE DATA AND SITE SETTINGS RESTORIENG THE SDM CMS TO ITS DEFAULT CONFIGURATION!</b></i><p></div>
'), array('incmethod' => 'prepend', 'incpages' => array('SDMDevTools', 'core', 'errors', 'clearErrorLog', 'reset')));


switch ($sdmcore->determineRequestedPage()) {
    case 'core': // dispaly current core configuration
        $output = '<h1>SDM CMS CORE</h1><p>Below is a visual representation of the current state of CORE</p>' . $sdmcore->sdmCoreCurlGrabContent($sdmcore->getRootDirectoryUrl() . '/coreoverview.php');
        $options = array('incmethod' => 'overwrite', 'incpages' => array('core'));
        $sdmassembler->incorporateAppOutput($sdmassembler_dataObject, $output, $options);
        break;
    case 'errors': // display recent errors
        $output = trim('<h1>Site Errors</h1>' . str_replace('[', '<p style="font-size: .8em;overflow:auto;border: 2px solid #CC0066;border-radius: 3px;background: black;color: #CC0066; margin: 3px 3px 3px 3px; padding: 23px 23px 23px 23px;">[', str_replace('<br />', '</p>', nl2br(file_get_contents($sdmcore->getCoreDirectoryPath() . '/logs/sdm_core_errors.log')))));
        $options = array('incmethod' => 'overwrite', 'incpages' => array('errors'));
        $sdmassembler->incorporateAppOutput($sdmassembler_dataObject, $output, $options);
        break;
    case 'clearErrorLog': // clear error log
        $output = $sdmcore->sdmCoreCurlGrabContent($sdmcore->getRootDirectoryUrl() . '/clearErrorLog.php');
        $options = array('incmethod' => 'overwrite', 'incpages' => array('clearErrorLog'));
        $sdmassembler->incorporateAppOutput($sdmassembler_dataObject, $output, $options);
        break;
    case 'reset': // reset site to default configuration | This will erase all site data includeing content, error logs, and site settings.
        // make an independant cal to incorporateAppOutput() so we can overwrite the target wrapper
        $output = $sdmcore->sdmCoreCurlGrabContent($sdmcore->getRootDirectoryUrl() . '/reset.php');
        $options = array('incmethod' => 'overwrite', 'incpages' => array('reset'));
        $sdmassembler->incorporateAppOutput($sdmassembler_dataObject, $output, $options);
        break;
    default :
        $output = '<h3>SDM DEV TOOLS</h3>';
        $options = array('incpages' => array('SDMDevTools', 'core', 'errors', 'clearErrorLog', 'reset'));
        $sdmassembler->incorporateAppOutput($sdmassembler_dataObject, $output, $options);
        break;
}